replicaCount: 2

image:
  repository: ghcr.io/REPLACE_ME/guestbook-unir   # cámbialo por tu repo (el workflow lo sobreescribe)
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: guestbook.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

redis:
  enabled: false
  image: redis:7-alpine
  port: 6379
  password: ""

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}
