apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/joaquinsosamartin/DevOpsPills_UNIR.git
    targetRevision: HEAD
    path: Video-12-Aplicando-GitOps-con-ArgoCD/manifests/guestbook
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true